<a href="https://colab.research.google.com/github/Roopanshi-Marwaha/Fraud_Ring_Detection/blob/main/Fraud_Ring_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()
#as i have them locally so just picking from there using this

Saving accounts.csv to accounts.csv
Saving alerts.csv to alerts.csv
Saving transactions.csv to transactions.csv

In [2]:
import pandas as pd

accounts = pd.read_csv('accounts.csv')
transactions = pd.read_csv('transactions.csv')
alerts = pd.read_csv('alerts.csv')

print(accounts.shape, transactions.shape, alerts.shape)
#printed rows and columns-->shape

(10000, 7) (1323234, 8) (1719, 9)

In [5]:
accounts.head()
#to see first 5 rows
#TX_BEHAVIOR_ID--> a group number controlling how that account normally transacts (used to simulate realistic behavior)
# IS_FRAUD here means the account itself is a known fraud account, not just one transaction

,ACCOUNT_ID,CUSTOMER_ID,INIT_BALANCE,COUNTRY,ACCOUNT_TYPE,IS_FRAUD,TX_BEHAVIOR_ID
0,0,C_0,184.44,US,I,False,1
1,1,C_1,175.80,US,I,False,1
2,2,C_2,142.06,US,I,False,1
3,3,C_3,125.89,US,I,False,1
4,4,C_4,151.13,US,I,False,1

In [8]:
accounts['ACCOUNT_TYPE'].value_counts()
#ACCOUNT_TYPE: all 10,000 accounts are "I" so there's only one account type in this dataset, not a mix.
# That column won't be useful for us later (no variation = no signal)

ACCOUNT_TYPE
I    10000
Name: count, dtype: int64

In [9]:
accounts['IS_FRAUD'].value_counts()
IS_FRAUD: 1,685 out of 10,000 accounts (~16.8%) are fraud accounts. That's a high fraud rate so plenty of fraud examples to learn from, not a rare event problem

IS_FRAUD
False    8315
True     1685
Name: count, dtype: int64

In [10]:
accounts['COUNTRY'].value_counts()
#all US so this column is also useless, no variation.

COUNTRY
US    10000
Name: count, dtype: int64

In [12]:
accounts['TX_BEHAVIOR_ID'].value_counts()
#exactly 5 behavior groups, 2,000 accounts each, perfectly even split

TX_BEHAVIOR_ID
1    2000
2    2000
3    2000
4    2000
5    2000
Name: count, dtype: int64

In [16]:
pd.crosstab(accounts['TX_BEHAVIOR_ID'], accounts['IS_FRAUD'])
#This will show fraud count per behavior group

#fraud rates:-
# Group 1: 291/2000 = 14.6%
# Group 2: 330/2000 = 16.5%
# Group 3: 309/2000 = 15.5%
# Group 4: 358/2000 = 17.9%
# Group 5: 397/2000 = 19.9%
# There's a mild upward trend (group 5 has more fraud than group 1) but it's not a huge gap.

IS_FRAUD        False  True
TX_BEHAVIOR_ID
1                1709    291
2                1670    330
3                1691    309
4                1642    358
5                1603    397

So in accounts.csv. We now know:

10k accounts are there

only useful columns are IS_FRAUD (target-ish) and TX_BEHAVIOR_ID (weak feature),

COUNTRY & ACCOUNT_TYPE are dead weight.